/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ruggil.billgenerator.modules;

import billgenerator.BillGenerator;
import java.io.File;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Somnath Shirkule
 */
public class DatabaseSetting extends javax.swing.JFrame {

    /**
     * Creates new form DatabaseSetting
     */
    public DatabaseSetting() {
        setUndecorated(true);
        initComponents();
        setLocation(450,150);
        checkDb();
    }
    private void checkDb()
    {
        
        try{
            if(!BillGenerator.hitToDatabase())
            {
                JOptionPane.showMessageDialog(this, "Database Error.","ERROR",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Database Error.","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        finally{
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jdbcUrl = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jdbcDriver = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jdbcUsername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jdbcPassword = new javax.swing.JTextField();
        btnOk = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Enter JDBC Url:");

        jdbcUrl.setBackground(new java.awt.Color(187, 187, 187));
        jdbcUrl.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Enter JDBC Driver:");

        jdbcDriver.setBackground(new java.awt.Color(187, 187, 187));
        jdbcDriver.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Enter Database Username:");

        jdbcUsername.setBackground(new java.awt.Color(187, 187, 187));
        jdbcUsername.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Enter Database Password:");

        jdbcPassword.setBackground(new java.awt.Color(187, 187, 187));
        jdbcPassword.setForeground(new java.awt.Color(0, 0, 0));

        btnOk.setBackground(new java.awt.Color(76, 127, 0));
        btnOk.setForeground(java.awt.Color.white);
        btnOk.setText("OK");
        btnOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnOkMousePressed(evt);
            }
        });
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Database Settings");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ruggil/billgenerator/icons/Close Window_24px.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(jdbcPassword)
                    .addComponent(jLabel3)
                    .addComponent(jdbcUsername)
                    .addComponent(jLabel2)
                    .addComponent(jdbcDriver)
                    .addComponent(jLabel1)
                    .addComponent(jdbcUrl)
                    .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 112, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(17, 17, 17)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdbcUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdbcDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdbcUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdbcPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOk)
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel6MousePressed

    private void btnOkMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkMousePressed
        // TODO add your handling code here:
        String url = jdbcUrl.getText().trim();
        String driver = jdbcDriver.getText().trim();
        String username = jdbcUsername.getText().trim();
        String password = jdbcPassword.getText().trim();
        boolean dbResult = hitToDatabase(url,username,password,driver);
        if(dbResult)
        {
        try{
            File file = new File(System.getProperty("user.dir") + "\\dbbill.properties");
            //System.out.println(System.getProperty("user.dir"));
            if(!file.exists())
            {
                file.createNewFile();
            }
            FileWriter writer = new FileWriter(file);
            writer.write("url=" + url + "\n" + "driver=" + driver + "\n" + "username=" + username + "\n" + "password=" + password);
            writer.flush();
            writer.close();
            JOptionPane.showMessageDialog(this, "Connection saved successfully.","Success",JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            System.exit(0);
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex.toString(), "ERROR", HEIGHT);
        }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Enter valid database credentials.","ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnOkMousePressed
    private boolean hitToDatabase(final String turl, final String tuser, final String tpass, final String tdriver)
    {
        Connection con = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        try
        {
            Class.forName(tdriver);
            //System.out.print(Db.getJdbcUrl() + Db.getJdbcDriver() + Db.getJdbcUsername() + Db.getJdbcPassword());
            con = DriverManager.getConnection(turl,tuser,tpass);
            ps = con.prepareStatement("show tables");
            rs = ps.executeQuery();
            if(rs.next())
            {
                return true;
            }
            return false;
        }
        catch(ClassNotFoundException | SQLException ex)
        {
            Logger.getLogger(BillGenerator.class.getName()).log(Level.SEVERE, null, ex);
            return false;
        }
        finally
        {
            //con.close();

        }
    }
    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatabaseSetting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatabaseSetting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatabaseSetting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatabaseSetting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatabaseSetting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jdbcDriver;
    private javax.swing.JTextField jdbcPassword;
    private javax.swing.JTextField jdbcUrl;
    private javax.swing.JTextField jdbcUsername;
    // End of variables declaration//GEN-END:variables
}
