/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ruggil.billgenerator.modules;

import java.awt.Color;
import java.awt.HeadlessException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Somnath Shirkule
 */
public class MainScreen extends javax.swing.JFrame {
    private final Thread timerThread;
    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setUndecorated(true);
        initComponents();
        timerThread = new Thread(() -> {
            while(true)
            {
                int rHrs = new Date().getHours();
                int rMns = new Date().getMinutes();
                int rSec = new Date().getSeconds();
                int hrs = 0;
                String mHrs = "", mMns = "", mSec ="";
                if(String.valueOf(rMns).length() == 2)
                {
                    mMns = String.valueOf(rMns);
                }
                else if(String.valueOf(rMns).length() == 1)
                {
                    mMns = "0" + String.valueOf(rMns);
                }
                if(String.valueOf(rSec).length() == 2)
                {
                    mSec = String.valueOf(rSec);
                }
                else if(String.valueOf(rSec).length() == 1)
                {
                    mSec = "0" + String.valueOf(rSec);
                }
                if(rHrs>12)
                {
                    hrs = rHrs - 12;
                    if(String.valueOf(hrs).length() == 1)
                    {
                        mHrs = "0" + hrs;
                    }
                    else
                    {
                        mHrs = String.valueOf(hrs);
                    }
                }
                else
                {
                    if(String.valueOf(rHrs).length() == 1)
                    {
                        mHrs = "0" + hrs;
                    }
                    else
                    {
                        mHrs = String.valueOf(rHrs);
                    }
                }
                if(rHrs>12)
                {
                    userToShow.setText( mHrs + ":" + mMns + ":" + mSec + " PM"); 
                }
                else
                {
                    userToShow.setText( mHrs + ":" + mMns + ":" + mSec + " AM"); 
                }
                   
            }
        });
        timerThread.start();
        closeAllScreens();
    }
    
    //to close all active screens
    private void closeAllScreens()
    {
        try{
            //welcomeText1.setVisible(false);
            //welcomeText2.setVisible(false);
            billScreen.dispose();
            itemScreen.dispose();
        }
        catch(Exception ex)
        {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        menuAhu = new javax.swing.JLabel();
        menuLogout = new javax.swing.JLabel();
        menuUser = new javax.swing.JLabel();
        userToShow = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        welcomeText2 = new javax.swing.JLabel();
        billScreen = new javax.swing.JInternalFrame();
        itemScreen = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        userText1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passText1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        userIdText1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JLabel();
        btnEdit = new javax.swing.JLabel();
        btnDelete = new javax.swing.JLabel();
        btnClear = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.white);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ruggil/billgenerator/images/com.ruggil.billgenerator.images.png"))); // NOI18N

        menuAhu.setBackground(java.awt.Color.white);
        menuAhu.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        menuAhu.setForeground(new java.awt.Color(0, 0, 51));
        menuAhu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuAhu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ruggil/billgenerator/icons/Paycheque_24px.png"))); // NOI18N
        menuAhu.setText("Generate Bill");
        menuAhu.setOpaque(true);
        menuAhu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuAhuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuAhuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuAhuMousePressed(evt);
            }
        });

        menuLogout.setBackground(java.awt.Color.white);
        menuLogout.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        menuLogout.setForeground(new java.awt.Color(255, 51, 51));
        menuLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ruggil/billgenerator/icons/Close Window_24px.png"))); // NOI18N
        menuLogout.setText("Exit");
        menuLogout.setOpaque(true);
        menuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuLogoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuLogoutMousePressed(evt);
            }
        });

        menuUser.setBackground(java.awt.Color.white);
        menuUser.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        menuUser.setForeground(new java.awt.Color(0, 0, 51));
        menuUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ruggil/billgenerator/icons/Add Property_24px.png"))); // NOI18N
        menuUser.setText("Item Master");
        menuUser.setOpaque(true);
        menuUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuUserMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuUserMousePressed(evt);
            }
        });

        userToShow.setBackground(new java.awt.Color(222, 222, 222));
        userToShow.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        userToShow.setForeground(new java.awt.Color(51, 153, 0));
        userToShow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userToShow.setOpaque(true);
        userToShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userToShowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userToShowMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userToShowMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(14, Short.MAX_VALUE))
            .addComponent(menuAhu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(userToShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(menuAhu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuUser, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1290, Short.MAX_VALUE)
                .addComponent(userToShow, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainPanel.setBackground(new java.awt.Color(0, 0, 51));

        welcomeText2.setFont(new java.awt.Font("Ebrima", 1, 48)); // NOI18N
        welcomeText2.setForeground(java.awt.Color.white);
        welcomeText2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeText2.setText("DIGITAL BILL GENERATOR");
        welcomeText2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        billScreen.setBackground(new java.awt.Color(255, 255, 255));
        billScreen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        billScreen.setTitle("Bill Generator");
        billScreen.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ruggil/billgenerator/icons/Paycheque_24px.png"))); // NOI18N
        billScreen.setVisible(true);

        javax.swing.GroupLayout billScreenLayout = new javax.swing.GroupLayout(billScreen.getContentPane());
        billScreen.getContentPane().setLayout(billScreenLayout);
        billScreenLayout.setHorizontalGroup(
            billScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1094, Short.MAX_VALUE)
        );
        billScreenLayout.setVerticalGroup(
            billScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
        );

        itemScreen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        itemScreen.setTitle("Item Master");
        itemScreen.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ruggil/billgenerator/icons/Add Property_24px.png"))); // NOI18N
        itemScreen.setVisible(true);

        jPanel2.setBackground(java.awt.Color.white);

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("Enter Item Code:");

        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("Amount per piece:");

        jLabel5.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("Enter Item Descreption:");

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));

        btnAdd.setBackground(java.awt.Color.white);
        btnAdd.setForeground(new java.awt.Color(0, 0, 51));
        btnAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAdd.setText("Add");
        btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdd.setOpaque(true);
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAddMousePressed(evt);
            }
        });

        btnEdit.setBackground(java.awt.Color.white);
        btnEdit.setForeground(new java.awt.Color(0, 0, 51));
        btnEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEdit.setText("Edit");
        btnEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEdit.setOpaque(true);
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditMouseExited(evt);
            }
        });

        btnDelete.setBackground(java.awt.Color.white);
        btnDelete.setForeground(new java.awt.Color(0, 0, 51));
        btnDelete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDelete.setText("Delete");
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelete.setOpaque(true);
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteMouseExited(evt);
            }
        });

        btnClear.setBackground(java.awt.Color.white);
        btnClear.setForeground(new java.awt.Color(0, 0, 51));
        btnClear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnClear.setText("Clear");
        btnClear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClear.setOpaque(true);
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        userTable.setBackground(new java.awt.Color(255, 255, 255));
        userTable.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        userTable.setForeground(new java.awt.Color(0, 0, 51));
        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item Description", "Amount per Piece"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        userTable.setCellSelectionEnabled(true);
        userTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userTable.setDoubleBuffered(true);
        userTable.setName(""); // NOI18N
        userTable.setRowHeight(20);
        userTable.setRowMargin(2);
        userTable.setSelectionBackground(new java.awt.Color(0, 0, 51));
        userTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        userTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        userTable.setShowHorizontalLines(false);
        userTable.setShowVerticalLines(false);
        jScrollPane1.setViewportView(userTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userText1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(userIdText1))
                        .addGap(51, 51, 51)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passText1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(userText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(passText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(userIdText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout itemScreenLayout = new javax.swing.GroupLayout(itemScreen.getContentPane());
        itemScreen.getContentPane().setLayout(itemScreenLayout);
        itemScreenLayout.setHorizontalGroup(
            itemScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        itemScreenLayout.setVerticalGroup(
            itemScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel6.setText("V1.0.0 | Developed by Ruggil Technologies");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(billScreen)
            .addComponent(itemScreen)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(welcomeText2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(billScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(welcomeText2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAhuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAhuMousePressed
        // TODO add your handling code here:
        closeAllScreens();
        billScreen.setVisible(true);
    }//GEN-LAST:event_menuAhuMousePressed

    private void menuAhuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAhuMouseEntered
        // TODO add your handling code here:
        menuAhu.setBackground(new Color(222,222,222));
    }//GEN-LAST:event_menuAhuMouseEntered

    private void menuAhuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAhuMouseExited
        // TODO add your handling code here:
        menuAhu.setBackground(Color.WHITE);
    }//GEN-LAST:event_menuAhuMouseExited

    private void menuLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseEntered
        // TODO add your handling code here:
        menuLogout.setBackground(new Color(222,222,222));
    }//GEN-LAST:event_menuLogoutMouseEntered

    private void menuLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseExited
        // TODO add your handling code here:
        menuLogout.setBackground(Color.WHITE);
    }//GEN-LAST:event_menuLogoutMouseExited

    private void menuLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMousePressed
        // TODO add your handling code here:
         try
        {
            int result = JOptionPane.showConfirmDialog(this,"Sure? You want to Exit?", "Exit",
               JOptionPane.YES_NO_OPTION,
               JOptionPane.QUESTION_MESSAGE);
            if(result == JOptionPane.YES_OPTION){
               timerThread.stop();
                this.hide();
                this.dispose();
                System.exit(0);
            }else if (result == JOptionPane.NO_OPTION){
               
            }else {
               
            }
            
            
        }
        catch(HeadlessException ex)
        {
            JOptionPane.showMessageDialog(this,ex.toString(),"ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menuLogoutMousePressed

    private void menuUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuUserMouseEntered
        // TODO add your handling code here:
        menuUser.setBackground(new Color(222,222,222));
    }//GEN-LAST:event_menuUserMouseEntered

    private void menuUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuUserMouseExited
        // TODO add your handling code here:
        menuUser.setBackground(Color.WHITE);
    }//GEN-LAST:event_menuUserMouseExited

    private void menuUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuUserMousePressed
        // TODO add your handling code here
        closeAllScreens();
        itemScreen.setVisible(true);
    }//GEN-LAST:event_menuUserMousePressed
    
    private void userToShowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userToShowMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_userToShowMouseEntered

    private void userToShowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userToShowMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_userToShowMouseExited

    private void userToShowMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userToShowMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_userToShowMousePressed

    private void btnAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseEntered
        // TODO add your handling code here:
        btnAdd.setBackground(new Color(222,222,222));
    }//GEN-LAST:event_btnAddMouseEntered

    private void btnAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseExited
        // TODO add your handling code here:
        btnAdd.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnAddMouseExited

    private void btnEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseEntered
        // TODO add your handling code here:
        btnEdit.setBackground(new Color(222,222,222));
    }//GEN-LAST:event_btnEditMouseEntered

    private void btnEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseExited
        // TODO add your handling code here:
        btnEdit.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnEditMouseExited

    private void btnDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseEntered
        // TODO add your handling code here:
        btnDelete.setBackground(new Color(222,222,222));
    }//GEN-LAST:event_btnDeleteMouseEntered

    private void btnDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseExited
        // TODO add your handling code here:
        btnDelete.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnDeleteMouseExited

    private void btnClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseEntered
        // TODO add your handling code here:
        btnClear.setBackground(new Color(222,222,222));
    }//GEN-LAST:event_btnClearMouseEntered

    private void btnClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseExited
        // TODO add your handling code here:
        btnClear.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnClearMouseExited

    private void btnAddMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnAddMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedLookAndFeelException ex) {
                Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
            new MainScreen().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame billScreen;
    private javax.swing.JLabel btnAdd;
    private javax.swing.JLabel btnClear;
    private javax.swing.JLabel btnDelete;
    private javax.swing.JLabel btnEdit;
    private javax.swing.JInternalFrame itemScreen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel menuAhu;
    private javax.swing.JLabel menuLogout;
    private javax.swing.JLabel menuUser;
    private javax.swing.JTextField passText1;
    private javax.swing.JTextField userIdText1;
    private javax.swing.JTable userTable;
    private javax.swing.JTextField userText1;
    private javax.swing.JLabel userToShow;
    private javax.swing.JLabel welcomeText2;
    // End of variables declaration//GEN-END:variables
}
